# Generated by Django 2.2 on 2019-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(default='ABS', max_length=20),
            preserve_default=False,
        ),
    ]
