# Generated by Django 2.2.1 on 2019-05-21 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0002_musclegroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField(max_length=200, verbose_name='Comments to the workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscles_involved',
        ),
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Exercise image'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscles',
            field=models.ManyToManyField(related_name='exercises', to='trainings.MuscleGroup', verbose_name='Primary muscles involved'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(related_name='secondary', to='trainings.MuscleGroup', verbose_name='Secondary muscles involved'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(help_text='Instructions on how to perform an exercise', max_length=200, verbose_name='Exercise description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='Name of an exercise', max_length=50, verbose_name='Exercise name'),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(help_text='Name of a muscle group', max_length=50, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainings.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(verbose_name='Repetitions')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='trainings.WorkoutExercise')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
