# Generated by Django 2.2.1 on 2019-05-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20190521_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='repetitions',
            new_name='reps',
        ),
    ]
