# Generated by Django 2.2.1 on 2019-05-22 22:09

from django.db import migrations, models
import training_app.trainings.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20190522_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=training_app.trainings.models.exercise_image_upload, verbose_name='Exercise image'),
        ),
    ]
