# Generated by Django 2.2.1 on 2019-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0006_auto_20190522_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
