# Generated by Django 2.2.1 on 2019-05-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_musclegroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
