# Generated by Django 2.2.1 on 2019-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20190526_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercise-images', verbose_name='Exercise image'),
        ),
    ]
