# Generated by Django 2.2.2 on 2019-06-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20190608_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(help_text='Instructions on how to perform the exercise', max_length=200, verbose_name='Exercise description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, help_text='Illustrative image of the exercise', null=True, upload_to='exercise-images', verbose_name='Exercise image'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscles_involved',
            field=models.ManyToManyField(help_text='Muscles involved in the exercise', related_name='exercises', to='trainings.MuscleGroup', verbose_name='Muscles involved'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='Name of the exercise', max_length=50, verbose_name='Exercise name'),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(help_text='Name of the muscle group', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='comments',
            field=models.TextField(help_text='Comments to the workout', max_length=200, verbose_name='Comments to the workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(help_text='Date when the workout was performed'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(help_text='Exercise', on_delete=django.db.models.deletion.CASCADE, to='trainings.Exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(help_text='Workout which the exercise is part of', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainings.Workout'),
        ),
    ]
